In [1]:
from experiment import Experiment
from utils.behavior_data import BehaviorData
from visuals import Plotter
import torch
import numpy as np
from utils.state_data import StateData

bd = BehaviorData(minw = 24, maxw = 25, sortBy = "pid")
print(bd.features[bd.test[0]])
print(bd.features[bd.train[-1]])

tensor([440.0000,   3.0000,   2.5000,   2.5000,   2.6667,   2.0000,   1.0000,
          0.0000,   1.0000,   1.0000,   0.0000,   1.0000,   1.0000,   0.0000,
          1.0000,   0.0000,   0.0000,   1.0000,   1.0000,   0.0000,   1.0000,
          1.0000,   0.0000,   1.0000,   0.0000,   1.0000,   1.0000,   1.0000,
          0.0000,   0.0000,   0.0000,   1.0000,   1.0000,   0.0000,   1.0000,
          1.0000], dtype=torch.float64)
tensor([439.,   2.,   3.,   3.,   1.,   3.,   1.,   0.,   1.,   0.,   1.,   1.,
          0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   1.,   1.,   0.,
          0.,   1.,   1.,   0.,   1.,   1.,   0.,   0.,   1.,   1.,   0.,   0.],
       dtype=torch.float64)
tensor([0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)
